# Generated by Django 3.2 on 2021-04-27 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('ColumnSeparator', models.CharField(choices=[('Comma', 'Comma'), ('Space', 'Space')], default='Comma', max_length=50)),
                ('StringChar', models.CharField(choices=[('Apostrophe', 'Apostrophe'), ('Quotation Marks', 'Quotation Marks')], default='Quotation Marks', max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schema',
                'verbose_name_plural': 'Schemas',
            },
        ),
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Type', models.CharField(choices=[('FullName', 'FullName'), ('Job', 'Job'), ('Email', 'Email'), ('Text', 'Text'), ('Integer', 'Integer')], default='FullName', max_length=30)),
                ('From', models.IntegerField(default=None)),
                ('To', models.IntegerField(default=None)),
                ('Order', models.IntegerField(unique=True)),
                ('Schemas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Columns', to='FakeCsvApp.schemas', verbose_name='Schemas')),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
            },
        ),
    ]
