# Generated by Django 3.2 on 2021-05-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCsvApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='From',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='columns',
            name='Order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='columns',
            name='To',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
