# Generated by Django 3.2 on 2021-05-02 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCsvApp', '0003_auto_20210502_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadschemas',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 7, 3, 9, 809494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schemas',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 7, 3, 9, 808140, tzinfo=utc)),
        ),
    ]
