# Generated by Django 3.2 on 2021-05-02 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCsvApp', '0005_auto_20210502_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadschemas',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 9, 39, 23, 53271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schemas',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 9, 39, 23, 51919, tzinfo=utc)),
        ),
    ]
