# Generated by Django 3.2 on 2021-05-04 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCsvApp', '0006_auto_20210502_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemas',
            old_name='ColumnSeparator',
            new_name='Delimiter',
        ),
        migrations.RenameField(
            model_name='schemas',
            old_name='StringChar',
            new_name='QuoteChar',
        ),
        migrations.AlterField(
            model_name='downloadschemas',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 13, 38, 54, 50184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='downloadschemas',
            name='Schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DownloadSchemas', to='FakeCsvApp.schemas', verbose_name='schema'),
        ),
        migrations.AlterField(
            model_name='schemas',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 13, 38, 54, 48453, tzinfo=utc)),
        ),
    ]
