# Generated by Django 3.2 on 2021-05-04 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('FakeCsvApp', '0007_auto_20210504_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadschemas',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 14, 45, 25, 643881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schemas',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 14, 45, 25, 642566, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schemas',
            name='Delimiter',
            field=models.CharField(choices=[('Comma (,)', 'Comma (,)'), ('Semicolon (;)', 'Semicolon (;)')], default='Comma (,)', max_length=50),
        ),
        migrations.AlterField(
            model_name='schemas',
            name='QuoteChar',
            field=models.CharField(choices=[("Single-quote (')", "Single-quote (')"), ('Double-quote (")', 'Double-quote  (")')], default='Double-quote (")', max_length=50),
        ),
    ]
